# Clair v4 minimal configuration — bound to localhost (no external exposure)
http_listen_addr: "127.0.0.1:10080"    # API (used by clairctl/MCP)
introspection_addr: "127.0.0.1:6060"  # /healthz, /metrics

indexer:
  connstring: "host=127.0.0.1 port=5432 user=clair password=clair dbname=clair sslmode=disable"
  migrations: true

matcher:
  connstring: "host=127.0.0.1 port=5432 user=clair password=clair dbname=clair sslmode=disable"
  indexer_addr: "http://127.0.0.1:10080"
  migrations: true

notifier:
  connstring: "host=127.0.0.1 port=5432 user=clair password=clair dbname=clair sslmode=disable"
  migrations: true

updaters:
  sets: ["alpine", "aws", "rhel", "debian", "ubuntu", "oracle", "photon", "suse"]
