# Clair v4 minimal configuration - bound to localhost to avoid external exposure
http_listen_addr: "127.0.0.1:8080"
introspection_addr: "127.0.0.1:6060"

log:
  level: "info"
  format: "text"

indexer:
  # Local PostgreSQL service on localhost. For external DB, change host to your FQDN or IP.
  connstring: "host=127.0.0.1 port=5432 user=clair password=clair dbname=clair sslmode=disable statement_timeout=60000"
  scanlock_retry: 10
  layer_scan_concurrency: 5

matcher:
  connstring: "host=127.0.0.1 port=5432 user=clair password=clair dbname=clair sslmode=disable statement_timeout=60000"
  indexer_addr: "http://127.0.0.1:8080"

notifier:
  connstring: "host=127.0.0.1 port=5432 user=clair password=clair dbname=clair sslmode=disable statement_timeout=60000"
  delivery_interval: 1m
  poll_interval: 5m

updaters:
  sets:
    - "alpine"
    - "aws"
    - "rhel"
    - "debian"
    - "ubuntu"
    - "oracle"
    - "photon"
    - "suse"
