# ==============================================================================
# HexStrike AI MCP Server v6.0 - Docker Compose Configuration
# ==============================================================================
# This compose file provides easy deployment of HexStrike MCP server
# with proper network capabilities and volume mounts
# ==============================================================================

version: '3.8'

services:
  hexstrike-mcp:
    # Build configuration
    build:
      context: ..
      dockerfile: docker/Dockerfile

    # Container name for easy reference
    container_name: hexstrike-mcp-server
    
    # Image name and tag
    image: hexstrike-ai:v6.0
    
    # Network capabilities required for security tools
    # NET_RAW: Required for raw socket operations (nmap, masscan, etc.)
    # NET_ADMIN: Required for network interface manipulation
    cap_add:
      - NET_RAW
      - NET_ADMIN

    # Port mapping: Host:Container
    # Exposes MCP server on host port 8888
    ports:
      - "8888:8888"

    # Environment variables (optional)
    environment:
      - PYTHONUNBUFFERED=1
      # - DEBUG_MODE=false
      # - MCP_PORT=8888

    # Volumes: persist only logs
    volumes:
      - ./logs:/opt/hexstrike/logs

    # Restart policy suitable for production
    restart: unless-stopped

    # Health check configuration
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8888/health"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 15s

    # Network configuration (optional)
    # Use host network for full network access - enable only if required.
    # network_mode: "host"

    # Security options (optional - uncomment for stricter hardening if compatible)
    # security_opt:
    #   - no-new-privileges:true
    # read_only: true            # may break tools needing write access to /opt/hexstrike
    # tmpfs:
    #   - /tmp:rw,exec,size=256m # scratch space if read_only=true
    # cap_drop:
    #   - ALL                    # start from no caps, then add back the needed ones
    # user: "1000:1000"          # run as non-root if your tools allow it
    # ulimits:
    #   nofile: 65536
    # sysctls:
    #   net.ipv4.ping_group_range: "0 2147483647"

# Network configuration (optional)
# networks:
#   hexstrike-network:
#     driver: bridge
